---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    assignees:
      - "kemplail"
    reviewers:
      - "kemplail"
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "kemplail"
    reviewers:
      - "kemplail"
    groups:
      # Uniquement les mises à jour majeures des dépendances de production
      npm-prod-major:
        dependency-type: "production"
        update-types:
          - "major"
      # Uniquement les mises à jour mineures et correctives des dépendances de production
      npm-prod-minors:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Uniquement les mises à jour des dépendances de développement
      npm-dev:
        dependency-type: "development"
    commit-message:
      prefix: "dependabot-javascript"
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    assignees:
      - "kemplail"
    reviewers:
      - "kemplail"
    # Regroupe toutes les mises à jour dans une seule PR
    groups:
      all-ruby:
        patterns:
          - "*"
    commit-message:
      prefix: "dependabot-ruby"
    ignore:
      - dependency-name: "business"
        versions: ["1.1", "1.2"]
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "ruby"
